---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana