---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 9090
      targetPort: web
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
